[WIP] Feature/substrate integration
SyntropyNet/syntropy-agent pull request #8
Opened 2021-12-02 12:36 UTC by Povilaszva

2021-12-20 09:39 UTC, drgkaleda requested changes
1. Check error handling. Cannot continue if there was an error
2. Check substrate library for thread safety - maybe it needs a lock in Recv as well. Or maybe it does not need a write lock also.
3. Move structs declaration from code. Also make constants instead of hardcoded values.

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +const waitForMsg = time.Duration(1000) * time.Millisecond
Why not use here time.Second ?

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +const addressPath = "/etc/syntropy/address"
it was /etc/syntropy-agent subdir in other places like config package.
Why this dir has changed ?

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +		content, err := os.ReadFile(mnemonicPath)
Any specific reason to use Stat ?
I think it can be ReadFile from the beginning, and handle errors - it will fail same if file is missing.

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +		mnemonic = string(content)
If there was an error- content will not be valid.
Should exit  or fallback to Mnemonic generation, if there was an error.

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +		mnemonicFile.WriteString(mnemonic)
Cannot write to file, of OpenFile failed.

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +	addressFile.WriteString(bc.keyringPair.Address)
Cannot write to file if OpenFile returned error

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +	}
Should handle errors correctly
If there was an error - data (meta)  will be invalid

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +			ID      types.Hash
Its a good practive not to mix struct declaration and code.
Move this struct from function body.

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +		}
Don't do os.Exit
return error

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +
Need to check it Recv does not need locking as well

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +
Its a good practice to have URL as a const

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +		Url: ipfsUrl,
Don't ignore errors

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +	}
Errors handling. Return error

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +
Unused variable

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +		Info []byte
Do not mix struct declaration in code

2021-12-20 09:39 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +
Whats the point here of getting channel ?

2021-12-20 09:39 UTC, drgkaleda commented on internal/config/agent.go
> +	}
Why 2 times get variable ?
Also checking empty key for variable that was not set in this function

2021-12-20 09:39 UTC, drgkaleda commented on pkg/ipfs/ipfs.go
> +package ipfs
Don't think it is usefull as a separate package.
Maybe make it a subpackage of blockchain controller ?
Or just a function of blockchain package

2021-12-29 09:58 UTC, pauliusmiksys reviewed
Nice code 💯 easy readable

2021-12-29 09:58 UTC, pauliusmiksys commented on controller/blockchain/blockchain.go
> +	return body, nil
```suggestion
	return io.ReadAll(resp.Body)
```

2021-12-29 09:58 UTC, pauliusmiksys commented on controller/blockchain/blockchain.go
> +	entropy, _ := bip39.NewEntropy(256)
I am wondering why do we swallow error here

2021-12-29 09:58 UTC, pauliusmiksys commented on controller/blockchain/blockchain.go
> +	return len(b), err
```suggestion
	return len(b), nil
```

2021-12-30 08:41 UTC, drgkaleda commented on controller/blockchain/blockchain.go
>  	for {
No println in final code please

2021-12-30 09:12 UTC, drgkaleda commented on controller/blockchain/blockchain.go
> +	return len(b), err
Thanks for Your input here !

2021-12-30 09:18 UTC, drgkaleda commented
Blockchain part still needs some work on it.
But this code is not conflicting with other parts and will not brake anything.
LGTM. Merge.

2021-12-30 09:18 UTC, merged